# NumPy 

The main python library used in numerical data analysis is NumPy (or Numpy). It is a Linear Algebra Library for Python.  It is a very important library for Data Science with Python mainly because almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

This library has vast functionalities. But this lecture gives only an introduction to Numpy. 
Check out http://cs231n.github.io/python-numpy-tutorial/#numpy for some easy reference. Look up more official references at https://numpy.org/doc/stable/reference/

## Installating Numpy

**It is highly recommended to install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If Anaconda is already installed, install NumPy using the following commands on the terminal or command prompt by typing:**
    
    conda install numpy
    
**In case there is any trouble installing anaconda, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html) for further help.**

## Importing NumPy

Like any other python library, one needs to import numpy before using it as:

In [3]:
import numpy as np

# Numpy Arrays

A numpy array is a grid of values. The values in the array should all be of the same datatype, and is indexed by a tuple of nonnegative integers. Numpy arrays essentially come in two flavors: vectors and matrices. 
- Vectors are strictly 1-d arrays and 
- matrices are 2-d (a matrix can still have only one row or one column).

The number of dimensions is the rank of the array. The shape of an array is a tuple of integers giving the size of the array along each dimension. 

Numpy arrays can be intialised from nested Python lists, and the elements can be accessed using square brackets. 
NumPy arrays are the most commonly used feature of the Numpy library. Hence, arrays are focussed here in this lecture.


## Creating NumPy Arrays
There are different ways to create a NumPy array.

### Initialise with a Python List

The NumPy arrays can be created directly from a list or list of lists. 

In [16]:
#Create a list.
my_list = [100, 300, 500, 700, 900]
my_list

[100, 300, 500, 700, 900]

In [17]:
#Use the list to initialise a numpy array.
np.array(my_list)

array([100, 300, 500, 700, 900])

In [18]:
# Create a list of lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
# Initalise the array with the list of lists.
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Python Built-in Methods 

NumPy arrays can be also be generated using in-built python methods. 

### arange

The arange() method is used to return an evenly spaced values within a given interval.
The method has the following parameters: 
- **start** parameter (inclusive in the sequence)  
- **end** parameter (exclusive in the sequence)
- **step size** (optional parameter used to find the next element in the sequence) 


In [20]:
# Note the end item is excluded. 
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [21]:
# Using negative step factor gives a decreasing sequence.
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### zeros and ones

There are in-build methods to generate arrays of zeros or ones

In [22]:
# Generate 1-d array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# A 2-d array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Generate the 1-d array of ones. 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
# 2-d array of ones. 
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### linspace
This method will return evenly spaced numbers over a specified interval. The method returns **num** evenly spaced samples, calculated over the interval [start, stop].

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) 

The endpoint of the interval can optionally be excluded.

In [27]:
# Generate ten elements between 0 and 100
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [28]:
# Method can be used to generate finer granular sequence
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

This is an method for creating an identity matrix. This returns a 2-D array with ones on the diagonal and zeros elsewhere. Takes only a single parameter which determines dimension of the square matrix.

In [25]:
# Create a Identity matrix of size 3X3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random number array generator

Numpy can also be used to generate random number arrays in different ways:

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution
over ``[0, 1)``.


In [29]:
# Generate a random number array from uniform distribution in the interval [0,1].
np.random.rand(5)

array([0.49427634, 0.07324475, 0.16004454, 0.43072425, 0.71650414])

In [30]:
# Generate a 2-d array of random numbers
np.random.rand(5,5)

array([[0.39999597, 0.25078144, 0.72748554, 0.07167121, 0.72194979],
       [0.70965716, 0.42935407, 0.84732461, 0.97137021, 0.97707771],
       [0.57952056, 0.64676668, 0.08184656, 0.01800877, 0.80935485],
       [0.01025258, 0.29819175, 0.90135212, 0.1828951 , 0.3903211 ],
       [0.40701626, 0.29688642, 0.90071284, 0.99923898, 0.28203738]])

### randn

Unlike rand which is uniform, randn() returns a sample (or samples) from the "standard normal" distribution. 

In [27]:
# Generates a 1-d random sequence from normal distribution.
np.random.randn(4)

array([-1.05655066, -1.25846276, -0.37442948, -2.53389516])

In [45]:
# Generates a 2-d random array from a normal distribution.
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
This method can be used to generate one or more random integers between the interval
 - interval ranges from `low` (inclusive) to `high` (exclusive).
 

In [32]:
# Generate a single random integer between 1 and 100. 
np.random.randint(1,100)

30

In [31]:
# Generate a sequence of random numbers between 1 and 100
np.random.randint(1,100,10)

array([81, 94, 11, 30, 31, 51, 73, 72, 96, 72])

<html> <h2 style="font-style:italic; color:#FF0000;"> Try Out the following set of exercises based on your NumPy array knowledge. Sample output expected is shown in each case. </h2> </html>

#### Import NumPy as np

#### Create an array of 10 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

0.6207161656839242

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 0.80576876,  1.59013915, -0.83058308, -0.43438662,  0.32082871,
       -0.08545432, -2.38898797,  0.69319989, -1.33838304,  1.41138425,
       -0.43161849,  0.46178273,  1.06786063,  0.99071981,  0.35362432,
       -0.83075139, -1.82422782, -1.1244872 ,  0.00686246,  1.76708371,
        1.34143708,  0.4603623 , -1.22070798, -1.73240446, -0.75053019])

#### Create an array of 20 linearly spaced points between 0 and 1:

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

*********************************************************************************************************************

=====================================================================================================================

# Array Attributes and Methods

NumPy arrays have a set of in-build attributes and methods. 

In [34]:
# Create two numpy arrays as examples. 
arr = np.arange(50)
ranarr = np.random.randint(0,100,20)

In [35]:
# 1-d array - vector
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [36]:
# 1-d array of random numbers
ranarr

array([ 9, 53, 73, 81, 69, 30,  3, 28, 53, 37, 76,  1, 30,  3, 46, 25, 57,
       88, 54, 89])

## Reshape
The shape (dimensions) of the array can be changed using the reshape() method
This returns an array containing the same data with a new shape.

In [43]:
# Convert the 50 element 1-d array into a 2-d array. 
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

#### Create the following matrix:

In [38]:
# The created random array.
ranarr

array([ 9, 53, 73, 81, 69, 30,  3, 28, 53, 37, 76,  1, 30,  3, 46, 25, 57,
       88, 54, 89])

In [39]:
# Find the max value in the array
ranarr.max()

89

In [40]:
# Find the index of the maximum value
ranarr.argmax()

19

In [41]:
# Find the minimum value in the array
ranarr.min()

1

In [42]:
# Find the index of the minimum value
ranarr.argmin()

11

## Shape

As mentioned earlier, numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array. The shape of an array is a tuple of integers giving the size of the array along each dimension.

The size of a Numpy array can be retrieved using the attribute named "shape". Please note it is not a method. Attribute does not use "()" when evoked. 

In [45]:
# Size of a Vector
arr.shape

(50,)

In [46]:
# Change it to a 2-d array with 1 column. Notice the two sets of brackets for a 2-d array with one row.
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
# Change the shape of the array and check the shape attribute value.
arr.reshape(2,25).shape

(2, 25)

In [48]:
# Change the shape of the array again.
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [50]:
# Change the shape of the array and check the modified shape attribute
arr.reshape(25,2).shape

(25, 2)

<html> <h2 style="font-style:italic; color:#FF0000;"> Try Out the following set of exercises based on your NumPy array knowledge. Sample output expected is shown in each case. </h2> </html>

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### dtype

It is also easy to find the data type of the object in the array.

In [62]:
#Find the datatypes of the elements in the array.
int_arr = np.array([1,2,3])
int_arr.dtype

dtype('int64')

In [8]:
float_arr = np.array([1.0, 2.0, 3.0])   # Let numpy choose the datatype
float_arr.dtype

dtype('float64')

# Indexing Array Elements

As shown above, there are different ways to create a NumPy array. Once the array is created, it is possible to select elements or groups of elements from an array.

There are 
- **Simple bracket indexing"** -similar to python lists.
- **Slice indexing:** 
- **Integer array indexing:**
- **Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.



In [2]:
import numpy as np

In [51]:
#Creating sample array
my_arr = np.arange(0,11)
# Check the array
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [52]:
#Get a value at an index
my_arr[8]

8

In [53]:
#Get values in a range
my_arr[1:5]

array([1, 2, 3, 4])

In [54]:
#Get values in a range
my_arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting and Slicing

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [55]:
#Setting a value with index range (Broadcasting)
my_arr[0:5]=100

#Show
my_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
# Reset array, we'll see why I had to reset in  a moment
my_arr = np.arange(0,11)

#Show
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#Important notes on Slices
slice_of_arr = my_arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [59]:
my_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [60]:
#To get a copy, need to be explicit
arr_copy = my_arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [61]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [63]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [64]:
# Getting individual element value
arr_2d[1,0]

20

In [65]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [66]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [67]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing or Integer array indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [68]:
#Set up matrix
arr2d = np.zeros((10,10))

In [69]:
#Length of array
arr_length = arr2d.shape[1]

In [70]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [71]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [72]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Boolean Array indexing and Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.
Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [73]:
# Regenerate the 1-d array.
my_arr = np.arange(1,11)
my_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# Use arithematic expressions to output a boolean sequence.
my_arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [76]:
bool_arr = my_arr>4

In [77]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
my_arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
my_arr[my_arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

<html> <h2 style="font-style:italic; color:#FF0000;"> Try Out the following set of exercises based on your NumPy array indexing knowledge. Sample output expected is shown in each case. Careful not to run the cells preceding the output as you will loose the output. </h2> </html>

Given a few matrices, replicate the resulting matrix outputs:

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [1]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# INSERT CODE HERE .. 





array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [2]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


# INSERT CODE HERE .. 






20

In [3]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


# INSERT CODE HERE .. 





array([[ 2],
       [ 7],
       [12]])

In [4]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# INSERT CODE HERE .. 




array([21, 22, 23, 24, 25])

In [5]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

# INSERT CODE HERE .. 




array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

*********************************************************************************************************************

=====================================================================================================================

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [83]:
import numpy as np
arr = np.arange(0,10)

In [15]:
arr.sum?

In [84]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [85]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide

  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [88]:
# Also warning, but not an error instead infinity
1/arr

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide

  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [89]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Broadcasting Operations

Numpy arrays differ from a normal Python list arithmetic because of their ability to broadcast. 

In [3]:
#Check out the example where a single row gets duplicated and adds to 3X3 matrix 
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:

Array-1

[[0 0 0]

 [1 2 3]

 [4 5 6]]

Array-2

[10 11 12]



New Array:

[[10 11 12]

 [11 13 15]

 [14 16 18]]


<html> <h2 style="font-style:italic; color:#FF0000;"> Try Out a few more broadcasting exercises based on your NumPy array knowledge. Make up your own arrays with different sizes and experiment which arithematic operations would work with broadcasting. </h2> </html>

In [13]:
import numpy as np
# Three are numerous possibilities. Sample e.g.,
mat1 = np.eye(3)
mat2 = np.ones(3)
mat3 = [5]
mat4 = np.arange(0,10).reshape(2,5)

mat1 + mat2
mat1 + mat3

mat2 + mat3

#mat1 + mat4
mat4 + mat3

# Let the student explore more options with new numpy arrays! Define more arrays and 
# check the combinatinns that work and that don't!

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [91]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [14]:
np.max(arr) #same as arr.max()

9

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
np.log(arr)

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log

  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

<html> <h2 style="font-style:italic; color:#FF0000;"> Try Out the following set of exercises. </h2> </html>

Given the matrix, write code to output specific functions:

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat


325




#### Get the standard deviation of the values in mat






7.211102550927978


#### Get the sum of all the columns in mat

In [25]:
#sum(mat) # also works if it was across rows!


array([ 15,  40,  65,  90, 115])

<html> <h2 style="font-style:italic; color:#FF00FF;"> Data Analysis Exercise using NumPy Arrays. TBD </h2> </html>